
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
  auth_mfa_modules:
    - type: totp
  packages: !include_dir_named packages

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.1
  ip_ban_enabled: true
  login_attempts_threshold: 5

logger:
  default: warning
  logs:
    pyatv: critical
    homeassistant.components.apple_tv: critical
    homeassistant.components.switchbot.cover: critical
    homeassistant.components.switchbot.coordinator: critical
    homeassistant.components.switchbot: critical
    homeassistant.components.bluetooth.passive_update_coordinator: critical
    homeassistant.components.bluetooth.active_update_coordinator: critical
    homeassistant.components.bluetooth.manager: critical
    homeassistant.components.recorder: info
    sqlalchemy.engine.Engine: warning

recorder:
  db_url: "mysql://ha:ufEOx3ZH8NBwD2HEfnJquHbk@127.0.0.1/homeassistant?charset=utf8mb4"
  purge_keep_days: 365
  auto_purge: true
  commit_interval: 3
  exclude:
    entity_globs:
      - sensor.google_pollen_*
      - sensor.openmeteo_*
      - sensor.openuv_*
      - sensor.pollen_species_list_*_today
      - sensor.pollen_forecast_*_day_*

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/hass-bha-icons.js

lovelace:
  mode: yaml
  resources:
    - url: /local/community/lovelace-mushroom/mushroom.js
      type: module
    - url: /local/community/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /local/community/decluttering-card/decluttering-card.js
      type: module
    - url: /local/community/button-card/button-card.js
      type: module
    - url: /local/community/clock-weather-card/clock-weather-card.js
      type: module
    - url: /local/community/frigate-hass-card/frigate-hass-card.js
      type: module
    - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /local/community/modern-circular-gauge/modern-circular-gauge.js
      type: module
    - url: /local/community/lovelace-hourly-weather/hourly-weather.js
      type: module
    - url: /local/community/apexcharts-card/apexcharts-card.js
      type: module
  dashboards:
    lovelace-overview:
      mode: yaml
      title: Overview
      icon: mdi:view-dashboard
      show_in_sidebar: true
      filename: dashboards/overview/dashboard.yaml
    lovelace-computers:
      mode: yaml
      title: Computers
      icon: mdi:server
      show_in_sidebar: true
      filename: dashboards/computers/dashboard.yaml
    lovelace-environment:
      mode: yaml
      title: Environment
      icon: mdi:leaf
      show_in_sidebar: true
      filename: dashboards/environment/dashboard.yaml
    lovelace-rv:
      mode: yaml
      title: RV
      icon: mdi:caravan
      show_in_sidebar: true
      filename: dashboards/rv/dashboard.yaml
    lovelace-security:
      mode: yaml
      title: Security
      icon: mdi:cctv
      show_in_sidebar: true
      filename: dashboards/security/dashboard.yaml
    lovelace-spaces:
      mode: yaml
      title: Spaces
      icon: mdi:floor-plan
      show_in_sidebar: true
      filename: dashboards/spaces/dashboard.yaml
    lovelace-systems:
      mode: yaml
      title: Systems
      icon: mdi:home-automation
      show_in_sidebar: true
      filename: dashboards/systems/dashboard.yaml

sonos:
  media_player:
    hosts:
      - 192.168.3.20

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:home

# Built-in YAML includes
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Custom YAML entities
mqtt: !include includes/mqtt.yaml
template: !include_dir_merge_list includes/templates
notify: !include includes/notification_groups.yaml
climate: !include includes/climate.yaml
generic_hygrostat: !include includes/generic_hygrostat.yaml
binary_sensor: !include includes/binary_sensor.yaml
sensor: !include_dir_merge_list includes/sensors
utility_meter: !include includes/utility_meters.yaml
weather: !include includes/weather.yaml
fan: !include includes/fan.yaml
light: !include includes/light.yaml
