###############################################################################
# Plant care: Ficus religiosa (Bodhi tree) — constants, no helpers
###############################################################################

homeassistant:
  customize:
    plant.bodhi_tree:
      friendly_name: "Bodhi Tree (Ficus religiosa)"

plant:
  bodhi_tree:
    sensors:
      moisture: sensor.plant_sensor_d455_moisture
      temperature: sensor.plant_sensor_d455_temperature
      brightness: sensor.plant_sensor_d455_illuminance
      conductivity: sensor.plant_sensor_d455_conductivity

template:
  - variables:
      # ===== CSV-derived constants =====
      bodhi:
        # numeric ranges
        temp_min_c: 12
        temp_max_c: 38
        light_min_lux: 3500
        light_max_lux: 95000
        moist_min_pct: 20
        moist_max_pct: 65
        cond_min_uscm: 30
        cond_max_uscm: 2000
        # care text
        care_sunlight: "Enjoy sunlight, tolerant of partial shade"
        care_watering: "Water thoroughly when soil surface is dry"
        care_fertilization: "Dilute fertilizer per instructions; apply once monthly in spring and autumn"
        care_pruning: "Remove old, diseased, and dead leaves in a timely manner"
        care_soil: "Loose, fertile, well-drained loam"
        notes: "Origin: Asia, China; Family: Moraceae (Ficus). Flowering: Mar–Apr; fruit: May–Jun. Size: Diameter ≥20 cm, height 20–30 m. Environmental humidity: 30–85%."
      # MiFlora entities
      bodhi_temp_f_entity: sensor.plant_sensor_d455_temperature
      bodhi_moist_pct_entity: sensor.plant_sensor_d455_moisture
      bodhi_light_lux_entity: sensor.plant_sensor_d455_illuminance
      bodhi_cond_uscm_entity: sensor.plant_sensor_d455_conductivity

    # ----- live value sensors -----
    sensor:
      - name: "Bodhi Temperature °F"
        unique_id: 5cab30e5-26cd-4cc2-a9d8-251132a0fa6e
        unit_of_measurement: "°F"
        availability: "{{ has_value(bodhi_temp_f_entity) }}"
        state: "{{ states(bodhi_temp_f_entity) }}"

      - name: "Bodhi Moisture %"
        unique_id: 12259ba5-3061-40ee-b653-3b4fe6ca71af
        unit_of_measurement: "%"
        availability: "{{ has_value(bodhi_moist_pct_entity) }}"
        state: "{{ states(bodhi_moist_pct_entity) }}"

      - name: "Bodhi Light lux"
        unique_id: 79208b32-d763-4e19-8196-2be146ca9959
        unit_of_measurement: "lx"
        availability: "{{ has_value(bodhi_light_lux_entity) }}"
        state: "{{ states(bodhi_light_lux_entity) }}"

      - name: "Bodhi Conductivity µS/cm"
        unique_id: 71f9b530-815d-494f-9b22-9e169244dc40
        unit_of_measurement: "µS/cm"
        availability: "{{ has_value(bodhi_cond_uscm_entity) }}"
        state: "{{ states(bodhi_cond_uscm_entity) }}"

      # ----- pretty range strings from constants -----
      - name: "Bodhi Temperature Range"
        unique_id: 5da1e0e4-8d7f-4c45-9cc6-d7d570af2342
        state: >-
          {%- from 'units/base.jinja' import u_convert_value, u_humanize_value -%}
          {%- set temp_min_f = u_humanize_value(u_convert_value(bodhi.temp_min_c, 'c', 'f'), '°F') -%}
          {%- set temp_max_f = u_humanize_value(u_convert_value(bodhi.temp_max_c, 'c', 'f'), '°F') -%}
          {{- temp_min_f ~ '–' ~ temp_max_f -}}

      - name: "Bodhi Light Range"
        unique_id: 03477bb2-ef04-424c-a3b9-972a8cb181aa
        state: >-
          {%- from 'units/base.jinja' import u_humanize_value -%}
          {%- set light_min_lux = u_humanize_value(bodhi.light_min_lux) -%}
          {%- set light_max_lux = u_humanize_value(bodhi.light_max_lux, 'lx') -%}
          {{- light_min_lux ~ '–' ~ light_max_lux -}}

      - name: "Bodhi Moisture Range"
        unique_id: 8eda3aa6-1a75-4249-9fe7-d2207712928b
        state: >-
          {%- from 'units/base.jinja' import u_humanize_value -%}
          {%- set moist_min_pct = u_humanize_value(bodhi.moist_min_pct, '%') -%}
          {%- set moist_max_pct = u_humanize_value(bodhi.moist_max_pct, '%') -%}
          {{- moist_min_pct ~ '–' ~ moist_max_pct -}}

      - name: "Bodhi Conductivity Range"
        unique_id: e48b9130-71ca-4cac-acc9-82705022cf1c
        state: >-
          {%- from 'units/base.jinja' import u_humanize_value -%}
          {%- set cond_min_uscm = u_humanize_value(bodhi.cond_min_uscm) -%}
          {%- set cond_max_uscm = u_humanize_value(bodhi.cond_max_uscm) -%}
          {{- cond_min_uscm ~ '–' ~ cond_max_uscm ~ ' µS/cm' -}}

      # ----- care guidance aggregator -----
      - name: "Bodhi Care Action"
        unique_id: 8543c957-dd32-4b28-9814-542f10015ac5
        icon: "mdi:leaf"
        availability: >-
          {{ has_value('sensor.bodhi_temperature_degf')
            and has_value('sensor.bodhi_moisture') 
            and has_value('sensor.bodhi_light_lux') 
            and has_value('sensor.bodhi_conductivity_ms_cm') }}
        state: >
          {%- from 'units/base.jinja' import u_convert_value, u_humanize_value -%}
          {%- set t = states('sensor.bodhi_temperature_degf') | float(0) -%}
          {%- set m = states('sensor.bodhi_moisture') | float(0) -%}
          {%- set l = states('sensor.bodhi_light_lux') | float(0) -%}
          {%- set c = states('sensor.bodhi_conductivity_ms_cm') | float(0) -%}

          {%- set t_c = u_convert_value(t, 'f', 'c') | float(none) -%}

          {%- set temp_min_f = u_humanize_value(u_convert_value(bodhi.temp_min_c, 'c', 'f'), '°F') -%}
          {%- set temp_max_f = u_humanize_value(u_convert_value(bodhi.temp_max_c, 'c', 'f'), '°F') -%}
          {%- set light_min_lux = u_humanize_value(bodhi.light_min_lux) -%}
          {%- set light_max_lux = u_humanize_value(bodhi.light_max_lux, 'lx') -%}
          {%- set moist_min_pct = u_humanize_value(bodhi.moist_min_pct, '%') -%}
          {%- set moist_max_pct = u_humanize_value(bodhi.moist_max_pct, '%') -%}
          {%- set cond_min_uscm = u_humanize_value(bodhi.cond_min_uscm) -%}
          {%- set cond_max_uscm = u_humanize_value(bodhi.cond_max_uscm) -%}

          {%- set ns = namespace(out=[]) -%}
          {%- if not (bodhi.temp_min_c <= t_c <= bodhi.temp_max_c) -%}
            {%- if t_c < bodhi.temp_min_c -%}
              {%- set ns.out = ns.out + ['Move to warmer spot or bring indoors; target ' ~ temp_min_f ~ '–' ~ temp_max_f ~ '.'] -%}
            {%- else %}
              {%- set ns.out = ns.out + ['Reduce heat stress; diffuse light and water as needed; target ' ~ temp_min_f ~ '–' ~ temp_max_f ~ '.'] -%}
            {%- endif %}
          {%- endif %}
          {%- if not (bodhi.light_min_lux <= l <= bodhi.light_max_lux) -%}
            {%- if l < bodhi.light_min_lux -%}
              {%- set ns.out = ns.out + ['Increase light to ' ~ light_min_lux ~ '–' ~ light_max_lux ~ '; consider a grow light.'] -%}
            {%- else -%}
              {%- set ns.out = ns.out + ['Reduce intensity or diffuse sun; aim ' ~ light_min_lux ~ '–' ~ light_max_lux ~ '.'] -%}
            {%- endif -%}
          {%- endif %}
          {%- if not (bodhi.moist_min_pct <= m <= bodhi.moist_max_pct) -%}
            {%- if m < bodhi.moist_min_pct -%}
              {%- set ns.out = ns.out + ['Water thoroughly; maintain ' ~ moist_min_pct ~ '–' ~ moist_max_pct ~ '.'] -%}
            {%- else -%}
              {%- set ns.out = ns.out + ['Allow soil to dry toward ' ~ moist_min_pct ~ '–' ~ moist_max_pct ~ '; verify drainage.'] -%}
            {%- endif -%}
          {%- endif %}
          {%- if not (bodhi.cond_min_uscm <= c <= bodhi.cond_max_uscm) -%}
            {%- if c < bodhi.cond_min_uscm -%}
              {%- set ns.out = ns.out + ['Feed lightly; target EC ' ~ cond_min_uscm ~ '–' ~ cond_max_uscm ~ ' µS/cm.'] -%}
            {%- else -%}
              {%- set ns.out = ns.out + ['Flush pot to reduce salts; resume mild feeding after EC drops.'] -%}
            {%- endif -%}
          {%- endif %}
          {{- ns.out | join('\n') if ns.out else 'Optimal. Maintain current care.' -}}

      # ----- expose care text constants as read-only sensors -----
      - name: "Bodhi Sunlight"
        unique_id: 1b8d897f-bb9a-41f1-b88f-bd8728d1b9b4
        state: "{{ bodhi.care_sunlight }}"
      - name: "Bodhi Watering"
        unique_id: b83d6d99-3ef9-449e-ad9b-a51b4510cf51
        state: "{{ bodhi.care_watering }}"
      - name: "Bodhi Fertilization"
        unique_id: 58aec064-2c3b-435a-b5cf-86ff15b5937f
        state: "{{ bodhi.care_fertilization }}"
      - name: "Bodhi Pruning"
        unique_id: 7f23f0fc-28b8-429f-9427-5dc5155e7869
        state: "{{ bodhi.care_pruning }}"
      - name: "Bodhi Soil"
        unique_id: 3b87e214-3721-4e19-b051-1947c3144ee4
        state: "{{ bodhi.care_soil }}"
      - name: "Bodhi Notes"
        unique_id: e36accc7-f26d-4ce6-b95e-9cecee9f5914
        state: "{{ bodhi.notes }}"

    # ----- in-range flags from constants -----
    binary_sensor:
      - name: "Bodhi Temp OK"
        unique_id: e86f905a-c8a8-487f-8ccc-26048bfcdf5b
        availability: "{{ has_value('sensor.bodhi_temperature_degf') }}"
        state: >
          {%- from 'units/base.jinja' import u_convert_value, u_humanize_value -%}
          {%- set t = states('sensor.bodhi_temperature_degf') | float(none) -%}
          {%- set v = u_convert_value(t, 'f', 'c') | float(none) -%}
          {{- v is not none and bodhi.temp_min_c <= v <= bodhi.temp_max_c -}}

      - name: "Bodhi Light OK"
        unique_id: 80783ff3-809c-48d3-84c8-6d61ac6b1b5e
        availability: "{{ has_value('sensor.bodhi_light_lux') }}"
        state: >
          {%- set v = states('sensor.bodhi_light_lux') | float(none) -%}
          {{- v is not none and bodhi.light_min_lux <= v <= bodhi.light_max_lux -}}

      - name: "Bodhi Moisture OK"
        unique_id: 88c46303-fba5-42fd-9e55-5482add71cd6
        availability: "{{ has_value('sensor.bodhi_moisture') }}"
        state: >
          {%- set v = states('sensor.bodhi_moisture') | float(none) -%}
          {{- v is not none and bodhi.moist_min_pct <= v <= bodhi.moist_max_pct -}}

      - name: "Bodhi Conductivity OK"
        unique_id: 9c7b315c-5627-43d4-b13a-894b38103575
        availability: "{{ has_value('sensor.bodhi_conductivity_ms_cm') }}"
        state: >
          {%- set v = states('sensor.bodhi_conductivity_ms_cm') | float(none) -%}
          {{- v is not none and bodhi.cond_min_uscm <= v <= bodhi.cond_max_uscm -}}

      - name: "Bodhi All OK"
        unique_id: 15ba1128-c397-492d-8f3b-c7eeabb70c5d
        device_class: problem
        availability: >-
          {{ has_value('binary_sensor.bodhi_temp_ok')
            and has_value('binary_sensor.bodhi_light_ok') 
            and has_value('binary_sensor.bodhi_moisture_ok') 
            and has_value('binary_sensor.bodhi_conductivity_ok') }}
        state: >
          {{- is_state('binary_sensor.bodhi_temp_ok','on')
             and is_state('binary_sensor.bodhi_light_ok','on')
             and is_state('binary_sensor.bodhi_moisture_ok','on')
             and is_state('binary_sensor.bodhi_conductivity_ok','on') -}}
