# =================== Google Pollen - Nearby ===================
- platform: rest
  name: Google Pollen Nearby
  unique_id: google_pollen_nearby
  scan_interval: 600
  timeout: 8
  resource_template: >-
    {% set plat = states('sensor.aaron_latitude') | float(0) %}
    {% set hlat = states('sensor.home_latitude')  | float(0) %}
    {% set plon = states('sensor.aaron_longitude') | float(0) %}
    {% set hlon = states('sensor.home_longitude')  | float(0) %}
    {% set lat = plat if plat != 0 else hlat %}
    {% set lon = plon if plon != 0 else hlon %}
    {% set ok = lat != 0 and lon != 0 %}
    {{ 'https://pollen.googleapis.com/v1/forecast:lookup' if ok else 'http://127.0.0.1:65535/' }}
  method: GET
  params:
    location.latitude: >-
      {% set plat = states('sensor.aaron_latitude') | float(0) %}
      {% set hlat = states('sensor.home_latitude')  | float(0) %}
      {{ plat if plat != 0 else hlat }}
    location.longitude: >-
      {% set plon = states('sensor.aaron_longitude') | float(0) %}
      {% set hlon = states('sensor.home_longitude')  | float(0) %}
      {{ plon if plon != 0 else hlon }}
    days: 5
    languageCode: en
    key: !secret google_pollen_api_key
  headers:
    Accept: application/json
    User-Agent: HomeAssistant
    Cache-Control: no-cache
  availability: >-
    {% set plat = states('sensor.aaron_latitude')  | float(0) %}
    {% set plon = states('sensor.aaron_longitude') | float(0) %}
    {% set hlat = states('sensor.home_latitude')   | float(0) %}
    {% set hlon = states('sensor.home_longitude')  | float(0) %}
    {% set lat = plat if plat != 0 else hlat %}
    {% set lon = plon if plon != 0 else hlon %}
    {{ not (lat == 0 and lon == 0) }}
  value_template: >-
    {% if value_json is mapping and value_json.error is not defined %}
      {% set di = value_json.get('dailyInfo') or [] %}
      {{ states(this.entity_id) if (di | count) == 0 else now().isoformat() }}
    {% else %}
      {{ states(this.entity_id) }}
    {% endif %}
  json_attributes:
    - dailyInfo
    - plantInfo

# =================== Google Pollen - Home =====================
- platform: rest
  name: Google Pollen Home
  unique_id: google_pollen_home
  scan_interval: 600
  timeout: 8
  resource_template: >-
    {% set lat = states('sensor.home_latitude')  | float(0) %}
    {% set lon = states('sensor.home_longitude')  | float(0) %}
    {% set ok = lat != 0 and lon != 0 %}
    {{ 'https://pollen.googleapis.com/v1/forecast:lookup' if ok else 'http://127.0.0.1:65535/' }}
  method: GET
  params:
    location.latitude: >-
      {{ states('sensor.home_latitude') | float(0) }}
    location.longitude: >-
      {{ states('sensor.home_longitude') | float(0) }}
    days: 5
    languageCode: en
    key: !secret google_pollen_api_key
  headers:
    Accept: application/json
    User-Agent: HomeAssistant
    Cache-Control: no-cache
  availability: >-
    {% set lat = states('sensor.home_latitude')  | float(0) %}
    {% set lon = states('sensor.home_longitude') | float(0) %}
    {{ not (lat == 0 and lon == 0) }}
  value_template: >-
    {% if value_json is mapping and value_json.error is not defined %}
      {% set di = value_json.get('dailyInfo') or [] %}
      {{ states(this.entity_id) if (di | count) == 0 else now().isoformat() }}
    {% else %}
      {{ states(this.entity_id) }}
    {% endif %}
  json_attributes:
    - dailyInfo
    - plantInfo

# =================== Google Pollen - RV =======================
- platform: rest
  name: Google Pollen RV
  unique_id: google_pollen_rv
  scan_interval: 600
  timeout: 8
  resource_template: >-
    {% set rlat = states('sensor.rv_latitude')   | float(0) %}
    {% set alat = states('sensor.aaron_latitude')| float(0) %}
    {% set hlat = states('sensor.home_latitude') | float(0) %}
    {% set rlon = states('sensor.rv_longitude')    | float(0) %}
    {% set alon = states('sensor.aaron_longitude') | float(0) %}
    {% set hlon = states('sensor.home_longitude')  | float(0) %}
    {% set lat = rlat if rlat != 0 else (alat if alat != 0 else hlat) %}
    {% set lon = rlon if rlon != 0 else (alon if alon != 0 else hlon) %}
    {% set ok = lat != 0 and lon != 0 %}
    {{ 'https://pollen.googleapis.com/v1/forecast:lookup' if ok else 'http://127.0.0.1:65535/' }}
  method: GET
  params:
    location.latitude: >-
      {% set rlat = states('sensor.rv_latitude')   | float(0) %}
      {% set alat = states('sensor.aaron_latitude')| float(0) %}
      {% set hlat = states('sensor.home_latitude') | float(0) %}
      {{ rlat if rlat != 0 else (alat if alat != 0 else hlat) }}
    location.longitude: >-
      {% set rlon = states('sensor.rv_longitude')    | float(0) %}
      {% set alon = states('sensor.aaron_longitude') | float(0) %}
      {% set hlon = states('sensor.home_longitude')  | float(0) %}
      {{ rlon if rlon != 0 else (alon if alon != 0 else hlon) }}
    days: 5
    languageCode: en
    key: !secret google_pollen_api_key
  headers:
    Accept: application/json
    User-Agent: HomeAssistant
    Cache-Control: no-cache
  availability: >-
    {% set rlat = states('sensor.rv_latitude')   | float(0) %}
    {% set rlon = states('sensor.rv_longitude')  | float(0) %}
    {% set alat = states('sensor.aaron_latitude')| float(0) %}
    {% set alon = states('sensor.aaron_longitude')| float(0) %}
    {% set hlat = states('sensor.home_latitude') | float(0) %}
    {% set hlon = states('sensor.home_longitude')| float(0) %}
    {% set lat = rlat if rlat != 0 else (alat if alat != 0 else hlat) %}
    {% set lon = rlon if rlon != 0 else (alon if alon != 0 else hlon) %}
    {{ not (lat == 0 and lon == 0) }}
  value_template: >-
    {% if value_json is mapping and value_json.error is not defined %}
      {% set di = value_json.get('dailyInfo') or [] %}
      {{ states(this.entity_id) if (di | count) == 0 else now().isoformat() }}
    {% else %}
      {{ states(this.entity_id) }}
    {% endif %}
  json_attributes:
    - dailyInfo
    - plantInfo
