- binary_sensor:
    - name: Laptop Status Alarm
      device_class: problem
      availability: "{{ has_value('binary_sensor.laptop_overall_status_ok') }}"
      state: "{{ is_state('binary_sensor.laptop_overall_status_ok','off') }}"
    - name: Desktop Status Alarm
      device_class: problem
      availability: "{{ has_value('binary_sensor.desktop_bq063ig_overall_status_ok') }}"
      state: "{{ is_state('binary_sensor.desktop_bq063ig_overall_status_ok','off') }}"
    - name: Frigate Status Alarm
      device_class: problem
      availability: "{{ has_value('binary_sensor.frigate_overall_status_ok') }}"
      state: "{{ is_state('binary_sensor.frigate_overall_status_ok','off') }}"
    - name: OPNSense Status Alarm
      device_class: problem
      availability: "{{ has_value('binary_sensor.opnsense_overall_status_ok') }}"
      state: "{{ is_state('binary_sensor.opnsense_overall_status_ok','off') }}"
    - name: RaspberryPi Status Alarm
      device_class: problem
      availability: "{{ has_value('binary_sensor.raspberrypi4_overall_status_ok') }}"
      state: "{{ is_state('binary_sensor.raspberrypi4_overall_status_ok','off') }}"

- sensor:
    - name: Laptop Battery Charge
      availability: "{{ has_value('sensor.laptop_battery_percent') }}"
      state: "{{ states('sensor.laptop_battery_percent') }}"
      unit_of_measurement: '%'
      device_class: battery
      state_class: measurement
