- platform: template
  panels:
    guest_bedroom_smoke_co_fire:
      name: "Guest Bedroom Smoke/CO/Fire"
      value_template: >-
        {% if is_state('binary_sensor.nest_protect_guest_room_smoke_status', 'on') %}
          triggered
        {% elif is_state('binary_sensor.nest_protect_guest_room_co_status', 'on') %}
          triggered
        {% elif is_state('binary_sensor.nest_protect_guest_room_heat_status', 'on') %}
          triggered
        {% else %}
          disarmed
        {% endif %}
      arm_away:
        service: script.turn_on
        target:
          entity_id: script.no_op
      arm_home:
        service: script.turn_on
        target:
          entity_id: script.no_op
      disarm:
        service: script.turn_on
        target:
          entity_id: script.no_op
