- platform: threshold
  name: Webcam Running
  entity_id: sensor.usb_current_monitor_ina219_current
  upper: 0.15                                # turn ON at ≥ 0.15 A
  hysteresis: 0.05                           # turn OFF at ≤ 0.10 A (0.15 - 0.05)
  device_class: running

- platform: bayesian
  name: Aaron Probably Home
  unique_id: 7e2b8c8a-4e3c-4b7a-9e2a-8c2e4b7a9e2a
  device_class: presence
  prior: 0.5
  probability_threshold: 0.7
  observations:
    - platform: state
      entity_id: device_tracker.pixel_9_pro_xl
      to_state: "home"
      prob_given_true: 0.9
      prob_given_false: 0.2
    - platform: state
      entity_id: device_tracker.iphone_work_you
      to_state: "home"
      prob_given_true: 0.85
      prob_given_false: 0.2
    - platform: state
      entity_id: sensor.pixel_9_pro_xl_wifi_connection        # Android Companion: wifi connection sensor
      to_state: "Watson Home"
      prob_given_true: 0.95
      prob_given_false: 0.1
    - platform: state
      entity_id: sensor.aaron_work_phone_ssid       # iOS Companion: SSID sensor
      to_state: "Watson Home"
      prob_given_true: 0.95
      prob_given_false: 0.1
