- platform: generic_thermostat
  name: Chicken Heat Lamp
  unique_id: chicken_heat_lamp
  heater: switch.chicken_coop_outlet_2
  target_sensor: sensor.chicken_coop_thermometer_temperature
  keep_alive: "0:03:00"
