- platform: template
  fans:
    attic_duct_fan:
      friendly_name: Attic Duct Fan
      availability_template: >-
        {{ has_value('switch.attic_duct_fan_switch_0') }}
      value_template: >-
        {{ is_state('switch.attic_duct_fan_switch_0', 'on') }}
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.attic_duct_fan_switch_0
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.attic_duct_fan_switch_0
    gym_floor_fan:
      friendly_name: Gym Floor Fan
      availability_template: >-
        {{ has_value('switch.floor_fan_outlet') }}
      value_template: >-
        {{ is_state('switch.floor_fan_outlet', 'on') }}
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.floor_fan_outlet
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.floor_fan_outlet
    gym_pedestal_fan:
      friendly_name: Gym Pedestal Fan
      availability_template: >-
        {{ has_value('switch.pedestal_fan') }}
      value_template: >-
        {{ is_state('switch.pedestal_fan', 'on') }}
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.pedestal_fan
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.pedestal_fan
