- platform: switch
  name: Front Porch Light
  entity_id: switch.front_porch_switch_0
- platform: switch
  name: Kitchen Porch Light
  entity_id: switch.kitchen_porch_switch_0
- platform: switch
  name: Back Porch Lights
  entity_id: switch.back_porch_switch_0
- platform: switch
  name: Garage Lights
  entity_id: switch.garage_lights_switch_0
- platform: switch
  name: Shop Lights
  entity_id: switch.shop_lights_switch_0
- platform: switch
  name: Fish Tank Light
  entity_id: switch.fish_tank_light_outlet
- platform: switch
  name: Living Room End Table Lamp
  entity_id: switch.living_room_end_table_lamp
- platform: switch
  name: Parlor Table Lamp
  entity_id: switch.parlor_table_lamp
- platform: switch
  name: Guest Bedroom Lamp
  entity_id: switch.guest_bedroom_lamp_socket_1
