# This notification group aggregates Aaron's personal and work cell phones
- platform: group
  name: "Aaron Phones"
  unique_id: aaron_phones
  services:
    - action: mobile_app_pixel_9_pro_xl
    - action: mobile_app_l144jy6rmq_iphone

# This notification group aggregates Aaron's personal and work cell phones and
# Ashley's ce phone.
- platform: group
  name: "Aaron and Ashley Phones"
  unique_id: aaron_and_ashley_phones
  services:
    - action: mobile_app_pixel_9_pro_xl
    - action: mobile_app_l144jy6rmq_iphone
    - action: mobile_app_ashleys_iphone
