# This notification group aggregates Aaron's personal and work cell phones
- platform: group
  name: "Aaron Phones"
  unique_id: 993317ac-6e54-438e-8757-9d2815a9ca51
  services:
    - action: mobile_app_pixel_9_pro_xl
    - action: mobile_app_l144jy6rmq_iphone

# This notification group aggregates Aaron's personal and work cell phones and
# Ashley's ce phone.
- platform: group
  name: "Aaron and Ashley Phones"
  unique_id: 022c9cb5-59b8-4627-9e42-4824cfafbf5d
  services:
    - action: mobile_app_pixel_9_pro_xl
    - action: mobile_app_l144jy6rmq_iphone
    - action: mobile_app_ashleys_iphone
