substitutions:
  name: bluetooth-basement
  friendly_name: Bluetooth Proxy - Basement

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"

esp32:
  board: esp32-poe-iso
  framework:
    type: esp-idf

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  #manual_ip:
  #  static_ip: 192.168.1.64
  #  gateway: 192.168.1.1
  #  subnet: 255.255.255.0

api:
  encryption:
    key: "444QJDSnMtZ7yLUbjMqS7YhwZmiwdzXGZR5Uzvut0hE="

logger:

ota:
  platform: esphome

dashboard_import:
  package_import_url: github://esphome/bluetooth-proxies/olimex-esp32-poe-iso.yaml@main

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: false

bluetooth_proxy:
  active: true

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic
