esphome:
  name: chicken-food-sensor
  friendly_name: Chicken Food Sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "hDPG7CDkUny7Jg8ujrc3ud9b9tLQKwcQz0q4hY1i0I8="

ota:
  - platform: esphome
    password: "6881e26a18c419adde31a1cab77f23a0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Chicken-Food-Sensor"
    password: "ExK7UYnT50b2"

captive_portal:

sensor:
  - platform: ultrasonic
    trigger_pin: GPIO22
    echo_pin: GPIO21
    name: 'Fill Level'
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - throttle_average: 60s
      - calibrate_polynomial:
          degree: 2
          datapoints:
            - 0.551 -> 0
            - 0.386 -> 50
            - 0.3035 -> 100
      - max:
          window_size: 60
          send_every: 5
      - exponential_moving_average:
          alpha: 0.2
#       - clamp:
#           min_value: 0
#           max_value: 100
#           ignore_out_of_range: true
