esphome:
  name: "current-sensor"
  friendly_name: Current Sensor
#  libraries:
#    - acs712=https://github.com/RobTillaart/ACS712.git
#  includes:
#    - acs712_component.h

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "L0UpHmld1njKl3VxjpHOpl7mHD5mVbPHeTmmEBxLoiU="

ota:
  platform: esphome
  password: "b2744fa1f1c5d5a3071eb63e8fe70b44"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Current-Sensor Fallback Hotspot"
    password: "De0ej6K9UOni"

captive_portal:

external_components:
#  - source: github://watsona4/esphome@acs712
#    components: [ acs712 ]
  - source:
      type: local
      path: my_components

sensor:
  - platform: acs712
    pin: A0
    mvpera: 66  # 20A model
    voltage: 3.3
    adc_steps: 4096
    current:
      name: Current
      unit_of_measurement: mA
      accuracy_decimals: 2
      filters:
        - median:
            window_size: 2
