substitutions:
  name: everything-presence-one-6dbad0
  friendly_name: Living Room Presence
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/everything-presence-one/everything-presence-one-sen0609-ble.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: pXSgT4xgwie45PstgEH8wVnkK7UG2pDZrvy7NxvNjnQ=

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
