esphome:
  name: outside-water
  friendly_name: Outside Water

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: "c5Ul16Bszzb6oHEzlQ9cxFbWZiwUlCWzKTW/kb9Iebw="

logger:
  level: VERBOSE

ota:
  - platform: esphome
    password: "b22ad958aae687a940a3a9109c98ef04"

sensor:
  - platform: dht
    pin: GPIO4
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    model: DHT22
    update_interval: 5s
