substitutions:
  name: parlor-table-lamp
  friendly_name: Parlor Table Lamp
packages:
  Athom_Technology.Smart_Plug_V2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: FEdjN7kyNHEFegCaeSDpJtPrXY1MJoJp6bBjDi2+WrU=
ota:
  platform: esphome
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
logger:

