substitutions:
  name: ratgdov25i-f6128e
  friendly_name: ratgdov2.5i f6128e
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: OVNe8PT0TzoakOVfZvM2AonWrnT+6DGWCPkwq+h/mrI=
ota:
  platform: esphome
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
