# home/packages/rv_presence_publish.yaml
automation:
  - id: rv_presence_publish_evidence
    alias: "RV presence: publish evidence to RV"
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.rv_near_home               # from your nearness helpers
          - binary_sensor.any_family_near_rv         # fixed templates from earlier
          - binary_sensor.two_family_near_rv
          - binary_sensor.user_near_rv
          - binary_sensor.aaron_phone_on_rv_wifi
          - binary_sensor.ashley_phone_on_rv_wifi
      - platform: time_pattern
        minutes: "/2"
    action:
      - service: mqtt.publish
        data:
          topic: "site/rv/cmd/presence"
          qos: 1
          retain: true
          payload: >
            {% set payload = {
              'ts': now().isoformat(),
              'ttl_s': 600,
              'rv_near_home': is_state('binary_sensor.rv_near_home','on'),
              'evidence': {
                'any_family_near_rv': is_state('binary_sensor.any_family_near_rv','on'),
                'two_family_near_rv': is_state('binary_sensor.two_family_near_rv','on'),
                'user_near_rv': is_state('binary_sensor.user_near_rv','on'),
                'aaron_ssid': is_state('binary_sensor.aaron_phone_on_rv_wifi','on'),
                'ashley_ssid': is_state('binary_sensor.ashley_phone_on_rv_wifi','on')
              }
            } %}
            {{ payload | tojson }}
